# Generated by Django 4.2.2 on 2023-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_place_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_to_visit',
            field=models.BooleanField(default=False),
        ),
    ]
