# Generated by Django 4.2.2 on 2023-08-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_place_is_to_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('monument', 'Monument / Historical Site'), ('forest', 'Forest'), ('mountain', 'Hill Station'), ('beach', 'Beach'), ('lake', 'Lake'), ('park', 'Park'), ('trek', 'Trekking Destination'), ('mall', 'Shopping Mall')], max_length=500),
        ),
    ]
